### ISSUE TITLE
Cannot apply the before-filter :require_login on my website's landing page because of timepiece

### ISSUE THREAD

**Issue by venkatesh920** [thombruce/timepiece#5]
If I apply a :require_login filter on my ApplicationController, then even timepiece's controller inherits it and hence stops working on the landing page because the filter fails.

How do I correct this?

**Comment by thombruce** [comment]
Take a look at this StackOverflow answer: http://stackoverflow.com/a/24293770

TimepieceController inherits from ApplicationController, so any filters set up there will be inherited too.

I think your best option would be to create an 'AuthenticatedController' like suggested in the SO answer, and then have all of the controllers you want to inherit the 'require_login' filter inherit from that:

`class MyController < AuthenticatedController`

That way you won't run into this issue with Timepiece or with other plugins which also inherit from ApplicationController.

I've checked your repo though and seen that you've added `except: :clock`, which will have fixed it for you no doubt. Just be aware that the current setup might cause issues with other plugins too if you use more down the line.

I might fix this in a future update though - thanks for bringing it to my attention. There's no real reason that timepiece _needs_ to inherit from ApplicationController. I'll make it something to consider ahead of the 0.3.0 update. :)

**Comment by venkatesh920** [comment]
Yup, `except: :clock` solved it for me for the time being. Thank you for your detailed response. :)
