### ISSUE TITLE
Deprecation warning with timepiece.css.scss

### ISSUE THREAD

**Issue by yunixon** [thombruce/timepiece#6]
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /.rvm/gems/ruby-2.3.3/gems/timepiece-0.4.0/vendor/assets/stylesheets/timepiece.css.scss to /.rvm/gems/ruby-2.3.3/gems/timepiece-0.4.0/vendor/assets/stylesheets/timepiece.scss

**Comment by thombruce** [comment]
Fixed with 0.4.1 release. Thanks for the heads up.
